services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d youtofy" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=${BACKEND_DATABASE_URL}
      - PORT=${AUTHENTICATION_PORT}
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-volume:
  pgadmin-volume:
